services:
  memos-mcp:
    # Build the image from the Dockerfile in the current directory.
    build: .
    # Set a consistent and identifiable container name.
    container_name: memos_mcp_server
    # Use a .env file to manage secrets and environment-specific configs.
    env_file:
      - .env
    # Map the container's internal port 8080 to host port 8088 to avoid conflicts.
    ports:
      - "8088:8080"
    # Connect the container to the pre-existing external network.
    networks:
      - apexsigma_net
    # Automatically restart the container unless it is explicitly stopped.
    restart: unless-stopped

# Define the external network that this service will connect to.
# This network must already exist and be managed by the main DevEnviro stack.
networks:
  apexsigma_net:
    external: true
