version: '3.8'

services:
  memos-api:
    build: .
    container_name: devenviro_memos_api
    ports:
      - "8091:8090" # Expose on a different host port to avoid conflicts
    env_file:
      - .env
    # Connect this service to the existing DevEnviro network
    networks:
      - apexsigma_net

  test-runner:
    build: .
    env_file:
      - .env
    environment:
      PYTHONPATH: /code # CORRECTED: Point to the project root
      API_HOST: memos-api
    networks:
      - apexsigma_net
    command: ["pytest", "-v", "/code/app/tests/"] # This is correct

networks:
  apexsigma_net:
    # This tells Docker Compose to use an existing network
    external: true
