[project]
name = "memos-as"
version = "0.1.0"
description = ""
authors = [
    {name = "SigmaDev11",email = "steynsean11@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "ruff (>=0.1.0,<0.2.0)",
    "mypy (>=1.0.0,<2.0.0)",
    "pytest (>=7.0.0,<8.0.0)",
    "pre-commit (>=3.0.0,<4.0.0)"
]

[tool.poetry]
packages = [{include = "memos"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
