# Filename: eod.toml
# Description: Generates a project-specific End-of-Day summary, automatically
# populating completed and open tasks from .md/tasks.project.as.md.

[command.eod.as]
prompt = """
AI Agent Instructions: ApexSigma End-of-Day Summary Drafter
Objective

Your goal is to generate a concise EOD report by gathering git commits and analyzing the central project task file for completed and open items.

Phase 1: Information Gathering

1.  **Get Git User & Commits:**
    -   Execute `git config user.name` to get the current user's name.
    -   Execute `git log --author="$(git config user.name)" --since="00:00:00" --pretty="format:- %s"` to get today's commits.

2.  **Analyze Project Tasks:**
    -   Check for the existence of `.md/tasks.project.as.md`.
    -   If it exists:
        -   Read the file and find all **completed tasks** (lines starting with `- [x]`).
        -   Read the file and find all **open tasks** (lines starting with `- [ ]`).
    -   If it doesn't exist, these sections will be skipped.


Phase 2: Draft the EOD Report

1.  **Assemble the Summary:** Create a Markdown-formatted string using the gathered information.

2.  **Format the Output:**

**EOD Report - (Today's Date)**


**✅ Code Accomplishments** *(List the git commit messages here. If none, state "No new commits today.")*


**☑️ Completed Tasks Today** *(List the completed tasks from the task file here.)*


**💡 Decisions & Learnings**
-   *(Placeholder: Note any key architectural decisions, new insights, or learnings.)*


**🚧 Blockers**
-   *(Placeholder: User to fill this in.)*


**🎯 Plan for Tomorrow (Remaining Tasks)** *(List the open tasks from the task file here. This sets up tomorrow's sod.)*


Phase 3: Final Output

1.  **Print to Console:** Output the entire formatted report.
"""
