groups:
  - name: memOS_API_Performance
    rules:
      - alert: HighAPIRequestRate
        expr: rate(http_requests_total[5m]) > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High API request rate detected"
          description: "API request rate is {{ $value }} requests/sec on {{ $labels.endpoint }}"

      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is {{ $value }}s for {{ $labels.method }} {{ $labels.endpoint }}"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.endpoint }}"

  - name: memOS_Memory_Operations
    rules:
      - alert: MemoryOperationFailures
        expr: rate(memory_operations_total{status="error"}[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Memory operation failures detected"
          description: "Memory operation failure rate is {{ $value }}/sec for {{ $labels.operation_type }}"

      - alert: SlowMemoryOperations
        expr: histogram_quantile(0.95, rate(memory_operation_duration_seconds_bucket[5m])) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow memory operations detected"
          description: "95th percentile memory operation duration is {{ $value }}s for {{ $labels.operation_type }}"

      - alert: LargeMemorySize
        expr: persistent_memory_size_bytes > 100000000  # 100MB
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Large persistent memory size detected"
          description: "Session {{ $labels.session_id }} has memory size of {{ $value | humanizeBytes }}"

  - name: memOS_AI_Performance
    rules:
      - alert: SlowAIInference
        expr: histogram_quantile(0.95, rate(ai_model_inference_duration_seconds_bucket[5m])) > 30
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Slow AI model inference detected"
          description: "95th percentile inference time is {{ $value }}s for {{ $labels.model }} {{ $labels.operation }}"

      - alert: LowTokenProcessingRate
        expr: token_processing_rate < 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Low token processing rate"
          description: "Token processing rate is {{ $value }} tokens/sec for {{ $labels.model }}"

      - alert: AIServiceErrors
        expr: rate(ai_service_requests_total{status="error"}[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "AI service errors detected"
          description: "AI service error rate is {{ $value }}/sec for {{ $labels.service }}"

      - alert: HighQueueSize
        expr: queue_size > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High queue size detected"
          description: "Queue {{ $labels.queue_name }} has {{ $value }} items"

  - name: memOS_System_Health
    rules:
      - alert: ServiceDown
        expr: up{job=~"memos.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "memOS service is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} is down"

      - alert: HighRequestsInFlight
        expr: http_requests_in_flight > 50
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of requests in flight"
          description: "{{ $value }} requests are currently being processed on {{ $labels.endpoint }}"
