server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs with service labels
  - job_name: container_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/containers/*.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            container_name: attrs.tag
      - regex:
          expression: '^(?P<container_id>[^_]+)_(?P<service>[^_]+)_'
          source: container_name
      - labels:
          service:
          container_id:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # AI Tool API service logs
  - job_name: ai_tool_api
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai_tool_api
          service: ai-tool-api
          __path__: /var/log/ai-tool-api/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            status_code: status_code
            response_time: response_time
            endpoint: endpoint
            session_id: session_id
      - labels:
          level:
          endpoint:
          status_code:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  # AI Tool Application logs
  - job_name: ai_tool_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai_tool_app
          service: ai-tool-app
          __path__: /var/log/ai-tool-app/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            session_id: session_id
            component: component
      - labels:
          level:
          session_id:
          component:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  # Memory Service logs
  - job_name: memory_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: memory_service
          service: memory-service
          __path__: /var/log/memory-service/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            operation: operation
            duration: duration
            memory_type: memory_type
            session_id: session_id
      - labels:
          level:
          operation:
          memory_type:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  # memOS API logs (from Docker container)
  - job_name: memos_api
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/memos_api'
        target_label: __service__
        replacement: 'memos-api'
      - source_labels: [__service__]
        target_label: service
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            endpoint: endpoint
            method: method
            status_code: status_code
            response_time: response_time
          source: output
      - labels:
          level:
          endpoint:
          method:
          status_code:
      - timestamp:
          source: timestamp
          format: RFC3339
          fallback_formats:
            - "2006-01-02T15:04:05Z07:00"
            - "2006-01-02 15:04:05"
      - output:
          source: message
